name: aoc2020
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  quiver: ^2.1.3
  dart_numerics: ^0.0.5

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
